# Generated by Django 5.0.1 on 2024-01-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxApp', '0003_phyfile_remove_physician_resume_physician_resumes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/Nurses/')),
            ],
        ),
        migrations.CreateModel(
            name='TeleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/telemedicines/')),
            ],
        ),
        migrations.CreateModel(
            name='VisaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/visas/')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='telemedicines',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='resume',
        ),
        migrations.AddField(
            model_name='nurse',
            name='resumes',
            field=models.ManyToManyField(to='rxApp.nurfile'),
        ),
        migrations.AddField(
            model_name='telemedicines',
            name='resumes',
            field=models.ManyToManyField(to='rxApp.telefile'),
        ),
        migrations.AddField(
            model_name='visa',
            name='resumes',
            field=models.ManyToManyField(to='rxApp.visafile'),
        ),
    ]
