# Generated by Django 5.0.1 on 2024-01-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxApp', '0005_state_alter_nurfile_file_alter_phyfile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HosFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hospital/')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='resumes',
            field=models.ManyToManyField(to='rxApp.hosfile'),
        ),
    ]
